FROM ubuntu:16.04

COPY ./build_env.sh /var/build_env.sh
RUN /var/build_env.sh

COPY ./spytest/bin/* /tmp/
RUN /tmp/upgrade_requirements.sh

# fix ixia ConfigElement config error
RUN sed -i 's/config.copy()/list(config)/g' /projects/scid/tools/ActivPython/2.7.18/lib/python2.7/site-packages/ixnetwork_restpy/assistants/batch/batchadd.py

USER $user